/** Deterministic detailed sample report for PDF preview / demos. */
export function buildFallbackSampleContent() {
  return [
    "All-services growth proposal",
    "Prepared for: Summit Peak Roofing LLC",
    "Location: Denver, CO",
    "Prepared by: Northstar Digital Agency",
    "Date: July 30, 2026",
    "Website reviewed: https://www.summitpeakroofing.example",
    "",
    "1) Cover note",
    "Hi there,",
    "",
    "Thank you for the chance to review how Summit Peak Roofing LLC shows up online for roofing customers across Denver, CO. We completed a live crawl of your website, checked key conversion paths, reviewed public reputation signals, and assessed readiness for Instagram/social and Google Ads.",
    "",
    "This proposal is written for you as the business owner. It explains what is working, what is costing you booked estimates, and exactly how Northstar Digital Agency will fix it through a combined plan: website conversion, local SEO, social proof, and paid search.",
    "",
    "Our goal is simple: more qualified homeowners requesting quotes from Summit Peak Roofing - and a clearer path from search or social into a phone call or form submission.",
    "",
    "2) What we reviewed",
    "We reviewed the following channels and pages (facts from the live audit only):",
    "",
    "- Live website crawl of the homepage and linked key pages",
    "- Homepage signals: HTTPS, title tags, H1 structure, hero/CTA, forms, phone, load speed",
    "- Key pages: Contact / Quote, About, Services, Gallery, Blog",
    "- Social presence: Instagram not detected on site; Facebook linked on site",
    "- Public reputation: Google 4.6 rating with 87 reviews",
    "- Paid-search readiness: conversion path, tracking readiness, landing-page clarity",
    "",
    "What looks strong today:",
    "- You already have a live website URL and public Google reviews (4.6 / 87), which is a real trust advantage many roofers still lack.",
    "- Facebook is linked from the site, so you are not starting from zero on social.",
    "",
    "3) Issues we found",
    "Below are the highest-impact gaps from the live review. Each one affects whether a homeowner stays long enough to request an estimate.",
    "",
    "1. Homepage title is generic and the meta description is missing",
    "Search results do not clearly say what you do, where you work, or why a Denver homeowner should click Summit Peak first. A missing meta description means Google invents a snippet - usually not your strongest sales message.",
    "",
    "2. Competing H1 headlines and thin homepage copy (about 180 words)",
    "The homepage does not tell a clear story: who you help, what services you offer, and what to do next. Thin copy also weakens local SEO for roofing + Denver intent.",
    "",
    "3. Quote form sits below the fold with no strong above-the-fold CTA",
    "On mobile especially, visitors should see one primary action immediately (Get a Quote or Call Now). When the form is buried, many leave before they ever see it.",
    "",
    "4. LocalBusiness schema is missing",
    "Search engines do not get a clean structured signal for your business name, service area, and contact details. That makes it harder to win rich results and local trust.",
    "",
    "5. Instagram is not connected; project gallery is thin",
    "Roofing sells on proof. Without a connected Instagram profile and a strong before/after gallery, you miss an easy path from project photos to quote requests.",
    "",
    "6. Landing path is not ready for paid search scale",
    "Before spending on Google Ads or Local Services Ads, the site needs a fast, clear, mobile quote path with tracking. Launching ads on a weak conversion path burns budget.",
    "",
    "4) Why this costs you jobs",
    "Homeowners comparing roofers move fast. If your search snippet is unclear, your homepage feels thin, or the quote path is hard to find, they call the next company in the results.",
    "",
    "That is especially expensive in Denver during storm season and peak repair windows - when demand spikes and competitors who look clearer online capture the overflow.",
    "",
    "Every weak CTA, missing trust page, thin gallery, or untracked ad click is a quote that never reaches your phone. The fix is not more random posting or more ad spend alone. It is a tighter system: message, pages, proof, and conversion.",
    "",
    "5) How we help",
    "Here is what Northstar Digital Agency will deliver under a full digital growth engagement (website, local SEO, Instagram/social, and Google Ads):",
    "",
    "Website conversion",
    "1. Rewrite the homepage hero with one clear promise, social proof, and a primary Get a Quote CTA",
    "2. Move the quote form above the fold and add click-to-call on every key mobile page",
    "3. Strengthen Contact, About, and Services pages so visitors can trust and convert quickly",
    "",
    "Local SEO foundations",
    "1. Write stronger title tags and meta descriptions for home and top service pages",
    "2. Add LocalBusiness schema and clean on-page structure for Denver roofing intent",
    "3. Expand useful service/city content without fluff - focused on booked estimates",
    "",
    "Instagram and social proof",
    "1. Connect Instagram to the website and optimize the profile bio CTA",
    "2. Build a project gallery that supports before/after proof",
    "3. Install a simple weekly posting system with location tags and quote CTAs",
    "",
    "Google Ads readiness and launch",
    "1. Confirm conversion tracking for calls and form fills before spend scales",
    "2. Align landing pages with search intent (repair, replacement, storm, insurance)",
    "3. Launch geo-fenced Google Search and/or Local Services Ads once the path converts",
    "",
    "6) What you get",
    "Deliverables in the first 30 days:",
    "",
    "- Priority punch-list of website and SEO fixes ranked by impact on booked jobs",
    "- Homepage and quote-path implementation (copy, CTA, form placement, mobile call)",
    "- Schema + title/meta updates on priority pages",
    "- Instagram connection plan + gallery/proof framework",
    "- Ads readiness checklist and recommended launch sequence with estimated ranges labeled as estimates",
    "- Weekly checkpoint calls and a simple report of calls, forms, and progress",
    "",
    "Timeline snapshot:",
    "- Week 1: audit walkthrough, priorities locked, homepage/CTA draft",
    "- Week 2: conversion path live, schema/titles in progress, social setup started",
    "- Week 3: proof gallery + posting system; ads tracking verified",
    "- Week 4: optional paid launch (if conversion path is healthy) + 30-day review",
    "",
    "7) Recommended next step",
    "If this matches what you want for Summit Peak Roofing LLC, reply to this proposal or book a short 20-minute call with Northstar Digital Agency.",
    "",
    "On that call we will:",
    "- Walk through the live issues on your site together",
    "- Confirm which services you want first (website only, full package, or phased)",
    "- Outline kickoff steps and owners so work can start within one business day",
    "",
    "You already have review strength and a live web presence. The opportunity is to turn that into a clearer, faster quote machine - then amplify it with SEO, social proof, and paid search when the foundation is ready.",
  ].join("\n");
}
