/** Deterministic sample report body for PDF preview / demos. */
export function buildFallbackSampleContent() {
  return [
    "Full intelligence — Summit Peak Roofing LLC",
    "Generated: 2026-07-28",
    "Website: https://www.summitpeakroofing.example",
    "",
    "1) Executive summary",
    "Summit Peak Roofing LLC is a residential roofing contractor in Denver, CO with a 4.6 Google rating across 87 reviews and a lead score of 78/100. Live homepage signals show a usable site, but thin service copy, missing LocalBusiness schema, and a weak quote CTA leave demand on the table. The strongest agency offer is a 30-day package: technical SEO cleanup, city/service pages, Local Services Ads readiness, and a review engine.",
    "",
    "2) Business & local presence snapshot",
    "- Industry: Roofing",
    "- Location: Denver, CO",
    "- Google: 4.6 (87 reviews)",
    "- Owner contact: found on site About page (medium confidence)",
    "- Social: Facebook present, Instagram thin, LinkedIn company page missing",
    "- Years in business estimate: 9",
    "",
    "3) Website & technical SEO findings",
    "- HTTPS: Yes",
    "- Title tag: Present but generic (“Home | Summit Peak”)",
    "- Meta description: Missing",
    "- Viewport / mobile: Present",
    "- Canonical: Missing",
    "- Open Graph: Partial",
    "- JSON-LD / LocalBusiness schema: Missing",
    "- H1 count: 2 (competing headlines)",
    "- Content depth: ~180 words on homepage",
    "- Images missing alt text: 6/11",
    "- Phone on page: Yes",
    "- Contact form: Present below the fold",
    "- Blog / proof content: Not found",
    "",
    "Website quality score: 54/100",
    "SEO opportunity score: 81/100",
    "",
    "4) Organic / local SEO opportunity",
    "Search demand for “roof repair Denver”, “roof replacement Aurora”, and storm-related queries is strong. Competitors outrank this site with dedicated service + city pages, FAQ schema, and recent project galleries. GBP looks claimed but under-optimized (few photos, inconsistent categories).",
    "",
    "Priority local SEO moves:",
    "- Build roof-repair, roof-replacement, and storm-damage pages for Denver + 3 suburbs",
    "- Add LocalBusiness + Service schema",
    "- Align NAP across GBP, Yelp, and website footer",
    "- Publish weekly project / insurance FAQ posts",
    "",
    "5) Paid ads & PPC opportunity",
    "PPC opportunity score: 76/100. The site can support Local Services Ads and Google Search once landing pages convert. Current homepage is not ad-ready (slow quote path, no trust bar above the fold).",
    "",
    "Recommended launch:",
    "- LSA for Roofing in Denver metro",
    "- Search campaigns for high-intent repair + replacement keywords",
    "- Dedicated landing pages with call tracking + form",
    "- Starting test budget: $80–$150/day with weekly creative refresh",
    "",
    "6) Marketing & content opportunity",
    "Marketing opportunity score: 72/100. Reviews are a strength; visual proof and storm-season content are weak. Instagram is sparse. No email nurture for estimate follow-up is visible.",
    "",
    "Channel priorities:",
    "- Review request automation after closed jobs",
    "- Before/after photo system for social + GBP",
    "- Storm-season SMS/email to past customers",
    "- Partner referrals with local realtors / property managers",
    "",
    "7) Priority recommendations (highest ROI first)",
    "1) Rewrite homepage + add above-the-fold quote CTA and click-to-call.",
    "2) Add LocalBusiness schema and unique title/meta on all key pages.",
    "3) Launch 4 city/service landing pages for paid + organic.",
    "4) Install call tracking and form notifications.",
    "5) Claim/optimize GBP categories, photos, and Q&A.",
    "6) Start Local Services Ads with conversion-ready pages.",
    "7) Stand up a review request workflow (text + email).",
    "8) Publish weekly project proofs and insurance FAQs.",
    "",
    "8) 30-day action plan",
    "Week 1: Technical cleanup (meta, schema, CTA, tracking).",
    "Week 2: Service/city pages live; GBP photo + category refresh.",
    "Week 3: LSA / Search ads live; review automation on.",
    "Week 4: Measure booked estimates; expand winning suburbs and offers.",
    "",
    "9) Suggested agency outreach pitch",
    "Hi — I reviewed Summit Peak Roofing’s online presence in Denver. You have strong reviews (4.6), but the site is leaving local search and paid demand on the table: missing schema, thin service pages, and a slow quote path. We put together a 30-day plan covering SEO fixes, city pages, and Local Services Ads readiness. Open to a quick 15-minute walkthrough this week?",
  ].join("\n");
}
