/** Deterministic sample report body for PDF preview / demos. */
export function buildFallbackSampleContent() {
  return [
    "Website growth proposal",
    "Prepared for: Summit Peak Roofing LLC",
    "Location: Denver, CO",
    "Prepared by: Peak Local Marketing",
    "Date: July 28, 2026",
    "Website reviewed: https://www.summitpeakroofing.example",
    "",
    "1) Cover note",
    "Hi there,",
    "",
    "We reviewed how Summit Peak Roofing LLC shows up online for roofing customers in Denver, CO. This short proposal highlights what is holding back more booked estimates — and exactly how Peak Local Marketing can help through website design & conversion.",
    "",
    "2) What we reviewed",
    "• Live website crawl of the homepage and key pages",
    "• Homepage signals: HTTPS, titles, hero/CTA, forms, phone, speed",
    "• Key pages: Contact, About, Services, Gallery, Blog",
    "• Public reputation: Google 4.6 (87 reviews)",
    "",
    "3) Issues we found",
    "1. Homepage title is generic and the meta description is missing",
    "2. Competing H1 headlines and thin homepage copy (~180 words)",
    "3. Quote form sits below the fold; no clear above-the-fold CTA",
    "4. LocalBusiness schema is missing",
    "5. Several images are missing alt text; project gallery is thin",
    "",
    "4) Why this costs you jobs",
    "When the online experience is unclear or missing trust and quote paths, homeowners move on to the next contractor. Every weak CTA, missing page, or thin local signal is a quote that never reaches your phone — especially during storm season when demand spikes.",
    "",
    "5) How we help",
    "Here is what Peak Local Marketing will do under Website design & conversion:",
    "1) Rewrite the homepage hero with one promise, proof, and primary Get a Quote CTA",
    "2) Move the contact form above the fold and add click-to-call on mobile",
    "3) Add LocalBusiness schema and stronger title tags on home and top service pages",
    "4) Build a project gallery that supports social proof and trust",
    "5) Improve page speed and mobile quote capture so visitors convert faster",
    "",
    "6) What you get",
    "• A clear punch-list of fixes prioritized by impact on booked jobs",
    "• Implementation support for copy, pages, and tracking",
    "• A 30-day action plan with weekly checkpoints",
    "• Simple reporting so you can see calls, forms, and progress",
    "",
    "7) Recommended next step",
    "If this matches what you want for Summit Peak Roofing LLC, reply to this report or book a short call with Peak Local Marketing. We will walk through the issues on your site, confirm priorities, and outline kickoff within one business day.",
  ].join("\n");
}
